#!/bin/sh

apt update
apt install software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt install python3.7
apt install python3-pip
python3.7 -m pip install -U checkov #to install or upgrade checkov)

checkov --directory ${PLUGIN_DIRECTORY} ${PLUGIN_FLAG}
