#!/bin/sh

apt update
apt upgrade
apt install -y wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
add-apt-repository ppa:deadsnakes/ppa
apt install -y python3.10
apt install -y python3.10-distutils
curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
#apt install -y python3.7-dev
#echo 'Install dev'
#python3.7 -m pip install --upgrade pip
#echo 'Install pip upgrade'
#python3.7 -m pip install -U multidict
#echo 'Install multi'
python3.10 -m pip install -U checkov #to install or upgrade checkov)
echo 'Install checkov'
checkov --directory ${PLUGIN_DIRECTORY} ${PLUGIN_FLAG}
